# Generated by Django 3.0.7 on 2020-07-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroid', models.ImageField(default='', upload_to='centroid/')),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='accounts.userImage')),
            ],
        ),
    ]
