# Generated by Django 3.0.7 on 2020-07-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200710_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroidimage',
            name='base_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centroid', to='accounts.userImage'),
        ),
        migrations.CreateModel(
            name='SobelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobel_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sobel', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentation_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negative', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='MedianImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='median', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='HistogramImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram_0_url', models.CharField(default='', max_length=256)),
                ('histogram_1_url', models.CharField(default='', max_length=256)),
                ('histogram_2_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histogram', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='GrayscaleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grayscale_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grayscale', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='GradientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradient', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='GaussianImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaussian_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaussian', to='accounts.userImage')),
            ],
        ),
        migrations.CreateModel(
            name='AverageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_url', models.CharField(default='', max_length=256)),
                ('base_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average', to='accounts.userImage')),
            ],
        ),
    ]
