export const PUSH_LOGIN = 'PUSH_LOGIN'
export const PUSH_SIGNUP = 'PUSH_SIGNUP'
export const RETRY_CONNECT = 'RETRY_CONNECT'
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE'
export const SET_IMAGE_URL = 'SET_IMAGE_URL'
export const RESET_IMAGE = 'RESET_IMAGE'